services:
  - type: web
    name: moonbloom-backend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://KAIT0:Qx0ZesHTNYx86UzL@myapp.mxu9yj6.mongodb.net/moonbloom?appName=MyApp
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        value: https://moonbloom-backend.onrender.com/api/auth/google/callback
      - key: CORS_ORIGIN
        value: https://moonbloom-frontend.onrender.com
      - key: APP_URL
        value: https://moonbloom-backend.onrender.com
      - key: DISABLE_JOBS
        value: false
      - key: REMINDER_CRON
        value: 0 20 * * *
